name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build_extension:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: ['11.0', '11.0.1']
        java:   ['17']

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

      - name: Setup Ghidra
        uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}

      - name: bodge
        run: chmod +x gradlew

      - name: Build Extension
        run: ./gradlew

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: Ps3GhidraScripts-${{ matrix.ghidra }}-${{ matrix.java }}-${{ env.SHORT_SHA }}
          path: dist
          retention-days: 1
          if-no-files-found: error

  push_release:
    if: github.event_name == 'push'
    needs: build_extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Download artifacts
        uses: actions/download-artifact@main
        with:
          merge-multiple: true
          path: artifact

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls artifact
          gh release create 1.0${{ GITHUB.RUN_NUMBER }} artifact/*.zip --target ${{ GITHUB.SHA }} -t 1.0${{ GITHUB.RUN_NUMBER }}

